# Generated by Django 4.1.4 on 2024-04-11 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_cobertura', models.PositiveIntegerField()),
                ('cobertura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobertura', to='myapp.cobertura')),
                ('pote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pote_cobertura', to='myapp.montapote')),
            ],
            options={
                'verbose_name': 'A - SelCobertura',
                'verbose_name_plural': 'A - SelCobertura',
            },
        ),
    ]
