# Generated by Django 4.1.4 on 2024-04-11 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_selcobertura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montapote',
            name='coberturas',
        ),
    ]
