# Generated by Django 4.1.4 on 2024-04-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_montapote_coberturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(choices=[('CARTAO', 'Cartão'), ('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro')], max_length=100, null=True),
        ),
    ]
