# Generated by Django 4.1.4 on 2024-03-18 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cobertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontaPote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(null=True)),
                ('coberturas', models.ManyToManyField(to='myapp.cobertura')),
                ('embalagem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embalagem', to='myapp.embalagem')),
            ],
            options={
                'verbose_name': 'B - MontaPote',
                'verbose_name_plural': 'B - MontaPote',
            },
        ),
        migrations.CreateModel(
            name='SelSabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_bolas', models.PositiveIntegerField()),
                ('pote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pote', to='myapp.montapote')),
                ('sabor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sabor', to='myapp.sabor')),
            ],
            options={
                'verbose_name': 'A - SelSabor',
                'verbose_name_plural': 'A - SelSabor',
            },
        ),
    ]
