# Generated by Django 4.1.4 on 2024-03-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_montapote_selsabor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SacolaItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('potes', models.ManyToManyField(to='myapp.montapote')),
            ],
            options={
                'verbose_name': 'C - SacolaItens',
                'verbose_name_plural': 'C - SacolaItens',
            },
        ),
    ]
