# Generated by Django 4.1.4 on 2024-03-18 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_sacolaitens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField()),
                ('pago', models.BooleanField()),
                ('itens_da_sacola', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sacolaitens')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'D - Pedido',
                'verbose_name_plural': 'D - Pedido',
            },
        ),
    ]
